### PR TITLE
Jupyterlab

### PR DESCRIPTION
**Pull request by pmreyes2**
Pull request of the jupyterlab branch

### CODE REVIEW

**Comment by pmreyes2** [comment]
So, I assume any of us can merge this pull request? Should I just merge it?

**Comment by asreimer** [comment]
Generally, it is best not to merge your own pull request. This is an ettiquette and/or development rules thing.

Let's revisit this during our weekly meeting tomorrow.

**Comment by pmreyes2** [comment]
Agreed. Also, I might add another cool feature for jupyter:
https://github.com/matplotlib/jupyter-matplotlib

**Comment by asreimer** [comment]
That's neat. Hold off on that. It provides an opportunity for us to discuss scope of PRs and avoiding making monolithic omnibus pull requests.

**Comment by asreimer** [comment]
Closing for now. I've made a ton of changes to the Dockerfile.

**Comment by pmreyes2** [comment]
> Closing for now. I've made a ton of changes to the Dockerfile.

Looking forward to see those changes.

**Pull request closed without merging**
