### PR TITLE
Resenlite compatible

### PR DESCRIPTION
**Pull request by ljlamarche**
This is a relatively major refactoring of the resen code.  Some major points:
- BucketManager class has been removed
- Resen and DockerHelper classes have been moved to their own file
- Error handling is now managed by the Resen and DockerHelper classes raising exceptions instead of returning status statements (#28)
- Local buckets are set-up with sudo privileges - default password `ganimede` (#40)
- Import/Export features have been implemented (#41)
- Mounting to `/home/jovyan/work` is no longer allowed
- This includes the bug fix in PR #39 , so we can delete that one if this is merged

Hopefully this is a big step forwards, but there  are still a few fairly major things I think we should  address before a first release.
- **Image naming convention:** When an image is imported/exported, what should the image name/tag be?  Is this something that is specified by the export user or the import user?  Do we want to use some kind of default convention?
- **Docker access:** Right now all calls to anything docker related are done through a single instantiation of the DockerClient class.  Would it make more sense to handle these with individual usages of `with ... as ...`?  This would prevent the socket from being permanently open, which might be cleaner.  It would also let us use different settings for different things, i.e., how we had to set a timeout of 5 minutes for the entire class even though this is only really needed for the image save step of export.
- **Architecture:** This code still has a lot of levels of abstraction.  One idea is that instead of a Resen class, we just have a Bucket class, where each bucket object represents a single resen bucket and can be acted on independently.  For instance:
```
new_bucket  = Bucket(name='new_bucket')
new_bucket.add_port()
new_bucket.add_storage()
new_bucket.create_container()
new_bucket.start()
new_bucket.stop()
new_bucket.export()
``` 
The Bucket class could do all input checking, raise errors for bad file paths, assign ports, ect.  It could also have it's own method to write it's parameters to the json file, so that might be easier to track.  A less extreme change would be to just reformat the dictionary that buckets are currently saved as so it's a little more concise.  BOTH THESE OPTIONS WOULD BE API BREAKING!  Whatever we want to do, we should make a decision BEFORE the release, because afterwards we'll be pretty locked in.

These are just some ideas but I'm sure there are others.  Let me know what you think and we can move forwards!

### CODE REVIEW

**Comment by ljlamarche** [comment]
One comment about testing - this is designed to work with the new, no conda version of resen-core, which doesn't have an image available yet on dockerhub.  In order to test this, you'll need to build a resen-core image, then manually add it to the list of valid cores in the Resen class (Resen.py line 830).  For instance, I added the following dictionary to the list of returned valid cores:
```
{"version":"latest", "repo":"resen-lite", "org":"earthcubeingeo", "image_id":'sha256:134707a783d88358bcf4a850cbf602134a26dd6381a41b3af9960b8298f8caf6', "repodigest":''}
```
You can keep this, but you'll want to change `version` and `repo` to be the tag and name of your docker image and `image_id` to the full image ID (can be found with `docker images --no-trunc`).

**Comment by ljlamarche** [comment]
Another thought about importing.  If a user imports a bucket, then removes that bucket, should we delete the image that was imported?  I feel like we should either remove that image or add it to the list of allowed cores, not just leave it sitting around on the users system...  Unless we envision users importing the same bucket multiple times, in which case we should probably check to see if the image ID already exists on the local system, and only load it from the tar file if it does not.

**Comment by ljlamarche** [comment]
This now includes all the modifications we discussed last Thursday, and should be ready for code review/testing.  After all that passes, I think this is set for release.

**Comment by pmreyes2** [comment]
@ljlamarche I am testing resen on the following system:
operating system:
- Linux  4.4.0-141-generic
- #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018
- x86_64

Docker version:
- Docker version 18.09.1, build 4c52b90

Python version:
- Python 3.5.2 (default, Nov 12 2018, 13:43:14)

When trying to export a bucket I got the following error:
```
>>> Are you sure you would like to continue? (y/n): y
Exporting bucket b0.  This will take several mintues.
/tmp/tmpytq40uqi
Traceback (most recent call last):
  File "/home/pablo/python/python3.5.2/bin/resen", line 9, in <module>
    load_entry_point('resen==2019.1.0rc2', 'console_scripts', 'resen')()
  File "/home/pablo/python/python3.5.2/lib/python3.5/site-packages/resen/resencmd.py", line 577, in main
    ResenCmd(res).cmdloop(intro)
  File "/usr/lib/python3.5/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.5/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/pablo/python/python3.5.2/lib/python3.5/site-packages/resen/resencmd.py", line 232, in do_export_bucket
    self.program.export_bucket(bucket_name, file_name, exclude_mounts=exclude_list, img_repo=img_name, img_tag=img_tag)
  File "/home/pablo/python/python3.5.2/lib/python3.5/site-packages/resen/Resen.py", line 641, in export_bucket
    status = self.dockerhelper.export_container(bucket, bucket_dir_path.joinpath(image_file_name), img_repo, img_tag)
  File "/home/pablo/python/python3.5.2/lib/python3.5/site-packages/resen/DockerHelper.py", line 201, in export_container
    with open(filename, 'wb') as f:
TypeError: invalid file: PosixPath('/tmp/tmpytq40uqi/b0_image.tar')
```

It might be something related to `Python 3.5.2` and `PosixPath`. I think we have encounter something similar before @asreimer ?

**Comment by pmreyes2** [comment]
Ok. To make the code compatible with Python 3.5 I added some `str()` to the `PosixPath` instances and was able to export a bucket. The changes were the following:
```
diff --git a/resen/DockerHelper.py b/resen/DockerHelper.py
index ce23925..6edde62 100644
--- a/resen/DockerHelper.py
+++ b/resen/DockerHelper.py
@@ -198,7 +198,7 @@ class DockerHelper():
             # save image as *.tar file
             image = self.docker.images.get(image_name)
             out = image.save()
-            with open(filename, 'wb') as f:
+            with open(str(filename), 'wb') as f:
                 for chunk in out:
                     f.write(chunk)
 
diff --git a/resen/Resen.py b/resen/Resen.py
index 65338a2..15ecfd7 100644
--- a/resen/Resen.py
+++ b/resen/Resen.py
@@ -652,22 +652,22 @@ class Resen():
 
                 source_dir = Path(mount[0])
                 mount_file_name = '{}_mount.tgz'.format(source_dir.name)
-                with tarfile.open(bucket_dir_path.joinpath(mount_file_name), "w:gz") as tar:
+                with tarfile.open(str(bucket_dir_path.joinpath(mount_file_name)), "w:gz") as tar:
                     print(source_dir, source_dir.name)
-                    tar.add(source_dir, arcname=source_dir.name)
+                    tar.add(str(source_dir), arcname=source_dir.name)
 
                 manifest['mounts'].append([mount_file_name, mount[1], mount[2]])
 
             # save manifest file
-            with open(bucket_dir_path.joinpath('manifest.json'),'w') as f:
+            with open(str(bucket_dir_path.joinpath('manifest.json')),'w') as f:
                 json.dump(manifest, f)
 
             # save entire bucket as tgz file
             with tarfile.open(outfile, 'w:gz') as tar:
                 print(bucket_dir_path)
-                for f in os.listdir(bucket_dir_path):
+                for f in os.listdir(str(bucket_dir_path)):
                     print(bucket_dir_path.joinpath(f), f)
-                    tar.add(bucket_dir_path.joinpath(f), arcname=f)
+                    tar.add(str(bucket_dir_path.joinpath(f)), arcname=f)
```

**Comment by pmreyes2** [comment]
The creation of the bucket took about 10 minutes. tar file was 1.7 GB
Now I expect similar `PosixPath` issues in the import_bucket.

**Comment by pmreyes2** [comment]
I have committed the changes to make the software compatible with Python3.5 and I pushed the commit to this branch (resenlite_compatible). I have tested the export/import bucket with mounted directories in the aforementioned system.

**Comment by ljlamarche** [comment]
Thanks @pmreyes2!  I did all my testing in python 3.6.7, so that was a good catch.  In general, we're not terribly consistent about when we're using `os.path` and the `pathlib` module, but that's something that can be tidied up later.  Also, bucket creation taking 10 minutes and producing an output file that is 1.7 GB is consistent with what I was experiencing on my laptop.

**Comment by pmreyes2** [comment]
When importing a bucket a folder is created where the files BUCKETNAME_image.tar and manifest.json are extracted as well as all the mount folders, i.e. FOLDERNAME_mount.tgz.
After BUCKETNAME_image.tar image is loaded with docker,  the manifest.json file is read, and the mounted folders are extracted, the files are not removed.
TODO (I could do it some time between the weekend and next week)
- Remove BUCKETNAME_image.tar after it has been loaded with docker
- Remove manifest.json after it has been read
- Remove all the FOLDERNAME_mount.tgz files after they have been successfully extracted.

**Comment by ljlamarche** [comment]
There is a particularly confusing message the comes up in `create_bucket` when the user is asked if they want to add any mounts.
```
Local directories can be mounted to /home/jovyan/mount in a bucket.  You can specify either r or rw privileges  for each directory mounted.  Nothing mounted will be included in an exported bucket.  Any scripts, data,ect. that you would like to persist in an exported bucket MUST be copied into another part of the bucket.
```
This is no longer accurate with how we've designed a exported bucket to include mounts.  What we should probably emphasis is that anything created not in a mounted directory will not be accessible outside the resen bucket environment and will be deleted when the bucket is deleted.  @asreimer , can you add this to you list of minor fixes?  I'm currently in the process of making sure the rest of the examples on the usage page of the documentation are correct, but we can just swap in the correct statement for this question right before releasing.

**Comment by asreimer** [comment]
There's an issue on windows that I'm working through. Resen crashes when using `get_container_size`.

**Comment by asreimer** [comment]
> There's an issue on windows that I'm working through. Resen crashes when using `get_container_size`.

Ah, yes, this again:

    with docker.APIClient() as apiclient:
        info = apiclient.containers(all=True, size=True, filters={'id':bucket['container']})[0]

We cannot use calls to the `apiclient` because it isn't properly initialized on all systems. If we want to use the `api` directly, we can do so with `self.docker.api`. This was a problem that popped up before when we were implementing the status bar for the pull image stuff.

I've made a commit that fixes the problem.

**Comment by asreimer** [comment]
All testing that I've done looks good now. Merging.

Expect another PR to follow soon.

**Pull request merged**
