### PR TITLE
[MNT]: Update install and usage docs

### PR DESCRIPTION
**Pull request by asreimer**
This PR is for updating the usage documentation following the changes implemented in #27 and to update the installation docs for installation of resen on Windows systems.

You can view this version of the readthedocs here: https://resen.readthedocs.io/en/mnt_update_windows_docs/

PR #27 needs to be merged before this.

### CODE REVIEW

**Comment by ljlamarche** [comment]
Looks good!  Couple things:
1. Missing screen shots for Windows Installation.  @asreimer , did you say you had these already, or do we need to create them still?  We can use @astib windows laptop if necessary.
2. The windows installation instructions are now very thorough.  Should I put together a similar description for installation on Mac?  I used Docker Desktop though, and I believe that was fairly straight forward.
3. It might be a good idea to link the "Installation" and the "Installing on Windows" pages.  "Installing on Windows" could be a sub-page to a general Installation page, or we could just link it to the "Windows" section in the Docker installation instructions section.  It looks like most of the trickiness is in installing Docker.

**Comment by asreimer** [comment]
I have screenshots and such. This isn't done yet.

**Comment by asreimer** [comment]
Ok, I think this is finally done from the windows perspective. Let's keep this open and update the docs after we have finished changing the resen command line interface (solidify the create_bucket workflow, etc).

**Comment by pmreyes2** [comment]
The usage documentation has been updated according to the latest resen command line interface changes.

**Comment by ljlamarche** [comment]
Looks good to me.  Did we intentionally reduce the TOC levels so there's no longer a sidebar to navigate between pages, or is that a remnant (or a weird version of read the docs I'm looking at)?

**Comment by asreimer** [comment]
@pmreyes2 didn't touch the index files, but somehow the TOC changed...

Weird. Need to look at this.

**Comment by asreimer** [comment]
Docs are building fine now and done.

**Pull request merged**
