### PR TITLE
[ENH]: First version of documentation

### PR DESCRIPTION
**Pull request by ljlamarche**
This provides some basic documentation for the first version of Resen.  The readthedocs page (https://resen.readthedocs.io/en/latest/) should be fully integrated.  It currently pulls from the readthedocs branch, but we can change that after merging.

### CODE REVIEW

**Review by pmreyes2 — COMMENTED** [review]
The documentation looks great. I did some corrections/additions to docs/usage.rst in your PR as another PR to your readthedocs branch.

**Comment by asreimer** [comment]
I just finished installing Docker on my Windows machine at home. We should update the install instructions for Windows and macOS to provide a tiny note about a couple things:

1) On windows, if you use virtualbox to run VMs, you can't use Docker Desktop. This is because Docker Desktop requires hyper-V to work, but you can't run both hyper-V and virtualbox at the same time
2) Docker Desktop on macOS doesn't work for macOS earlier than 10.10 Yosemite. Maybe this isn't a problem for most users.

Probably, it is sufficient to add something like: "Important! Read the instructions carefully! If you are already using virtualbox, install Docker Toolbox; do not install Docker Desktop." Maybe we can talk about this tomorrow.

Otherwise this looks great for a first version of documentation.

**Comment by ljlamarche** [comment]
Great, I'll add those points under the installation instructions.  Should we also recommend using Docker Toolbox for macOS earlier than Yosemite?

**Comment by astib** [comment]
We need to introduce what a 'bucket' is before saying how you can create them etc.

**Comment by asreimer** [comment]
I think we just need to add a bit more documentation as per the comments from the meeting we had last week and then this is good to go right?

**Comment by ljlamarche** [comment]
Ok, I added a diagram of the "Bucket Concept" and tried to clarify the paragraphs that describe it a little more.  If this looks ok to everyone, I think we're good to go!

**Comment by asreimer** [comment]
I think this is a good start and we'll add to it as we go from here on in. Merging.

**Comment by asreimer** [comment]
@ljlamarche can you change the read the docs page so it points to the develop branch now?

**Comment by ljlamarche** [comment]
Thanks @asreimer .  I modified the read the docs page.  We should be set now so I'm going  to go ahead and delete this branch.

**Pull request merged**
