### PR TITLE
[ENH]: Progress bar aware of the terminal dimensions

### PR DESCRIPTION
**Pull request by pmreyes2**
This PR addresses issue #63. 
The previous behavior is shown in the following GIF where each iteration generates a new line. The issue was fixed by increasing the number of columns of the terminal window.

progress_bar_old

After the fix the behavior is depicted in the following GIF. Inside the iteration loop of pulling the image, the dimensions of the terminal window are obtained before the print statement. The dimension of the progress bar is adjusted accordingly.

progress_bar_new

### CODE REVIEW

**Review by ljlamarche — APPROVED** [review]
Looks good!

**Comment by asreimer** [comment]
Is this ready for review? It is marked as a draft PR.

**Comment by ljlamarche** [comment]
I think so?  I may have even tested it, I was just going to double check before pulling it into develop.

**Comment by asreimer** [comment]
I can confirm that the progress bar adjusts in properly when the terminal window is resized (on linux), but I cannot reproduce the bug in #63 so I cannot confirm if this PR fixes #63

**Comment by asreimer** [comment]
For completeness, @ljlamarche confirmed this fixes #63

**Pull request merged**
